export const ROLES = Object.freeze({
  PLATFORM_ADMIN:'PLATFORM_ADMIN',
  TENANT_ADMIN:'TENANT_ADMIN',
  EXPORT_ADMIN:'EXPORT_ADMIN',
  TEAM_LEAD:'TEAM_LEAD',
  OPERATOR:'OPERATOR',
  WAREHOUSE:'WAREHOUSE',
  AUDITOR:'AUDITOR'
});

export const PERMISSIONS = Object.freeze({
  PLATFORM_STATUS_READ:'platform.status.read',
  PLATFORM_TENANTS_MANAGE:'platform.tenants.manage',
  TENANT_SETTINGS_READ:'tenant.settings.read',
  TENANT_SETTINGS_WRITE:'tenant.settings.write',
  USERS_READ:'users.read',
  USERS_MANAGE:'users.manage',
  CUSTOMERS_READ:'customers.read',
  CUSTOMERS_WRITE:'customers.write',
  SHIPMENTS_READ:'shipments.read',
  SHIPMENTS_WRITE:'shipments.write',
  TASKS_READ:'tasks.read',
  TASKS_WRITE:'tasks.write',
  DOCUMENTS_READ:'documents.read',
  DOCUMENTS_UPLOAD:'documents.upload',
  PICKUP_CONFIRM:'pickup.confirm',
  POD_UPLOAD:'pod.upload',
  PALLETS_READ:'pallets.read',
  PALLETS_WRITE:'pallets.write',
  REPORTS_READ:'reports.read',
  AUDIT_READ:'audit.read'
});

const P=PERMISSIONS;
export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.PLATFORM_ADMIN]: Object.freeze([P.PLATFORM_STATUS_READ,P.PLATFORM_TENANTS_MANAGE]),
  [ROLES.TENANT_ADMIN]: Object.freeze([P.TENANT_SETTINGS_READ,P.TENANT_SETTINGS_WRITE,P.USERS_READ,P.USERS_MANAGE,P.CUSTOMERS_READ,P.CUSTOMERS_WRITE,P.SHIPMENTS_READ,P.SHIPMENTS_WRITE,P.TASKS_READ,P.TASKS_WRITE,P.DOCUMENTS_READ,P.DOCUMENTS_UPLOAD,P.PICKUP_CONFIRM,P.POD_UPLOAD,P.PALLETS_READ,P.PALLETS_WRITE,P.REPORTS_READ,P.AUDIT_READ]),
  [ROLES.EXPORT_ADMIN]: Object.freeze([P.TENANT_SETTINGS_READ,P.USERS_READ,P.CUSTOMERS_READ,P.CUSTOMERS_WRITE,P.SHIPMENTS_READ,P.SHIPMENTS_WRITE,P.TASKS_READ,P.TASKS_WRITE,P.DOCUMENTS_READ,P.DOCUMENTS_UPLOAD,P.PICKUP_CONFIRM,P.POD_UPLOAD,P.PALLETS_READ,P.PALLETS_WRITE,P.REPORTS_READ,P.AUDIT_READ]),
  [ROLES.TEAM_LEAD]: Object.freeze([P.CUSTOMERS_READ,P.SHIPMENTS_READ,P.SHIPMENTS_WRITE,P.TASKS_READ,P.TASKS_WRITE,P.DOCUMENTS_READ,P.DOCUMENTS_UPLOAD,P.PICKUP_CONFIRM,P.POD_UPLOAD,P.PALLETS_READ,P.REPORTS_READ]),
  [ROLES.OPERATOR]: Object.freeze([P.CUSTOMERS_READ,P.SHIPMENTS_READ,P.SHIPMENTS_WRITE,P.TASKS_READ,P.TASKS_WRITE,P.DOCUMENTS_READ,P.DOCUMENTS_UPLOAD,P.REPORTS_READ]),
  [ROLES.WAREHOUSE]: Object.freeze([P.SHIPMENTS_READ,P.TASKS_READ,P.DOCUMENTS_READ,P.PICKUP_CONFIRM,P.POD_UPLOAD,P.PALLETS_READ,P.PALLETS_WRITE]),
  [ROLES.AUDITOR]: Object.freeze([P.TENANT_SETTINGS_READ,P.USERS_READ,P.CUSTOMERS_READ,P.SHIPMENTS_READ,P.TASKS_READ,P.DOCUMENTS_READ,P.PALLETS_READ,P.REPORTS_READ,P.AUDIT_READ])
});

export function normalizeRole(role){
  const r=String(role||'').trim().toUpperCase().replace(/[\s-]+/g,'_');
  return Object.values(ROLES).includes(r)?r:'';
}

export function permissionsForRole(role){
  return [...(ROLE_PERMISSIONS[normalizeRole(role)]||[])];
}

export function hasPermission(role, permission){
  return permissionsForRole(role).includes(String(permission||''));
}
